SET IDENTITY_INSERT [dbo].[COM_CONTENT] ON
INSERT INTO [dbo].[COM_CONTENT] ([ID], [FK_RELATIONID], [CONTENT], [CONTENTBLOB], [FK_TABLE], [CREATEDATE]) VALUES (1, N'0922365b-df99-4edd-952a-39f0a1e03cf8', N'<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; line-height: 25px; text-indent: 2em; color: rgb(51, 51, 51); font-family: &#39;Microsoft YaHei&#39;; font-size: 14px; white-space: normal; background-color: rgb(255, 255, 255);">寿光海联信息技术有限公司位于寿光市软件园核心区域--孵化大厦，是一家集产品研发、生产和销售于一体的民营高新技术企业。</p><p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; line-height: 25px; text-indent: 2em; color: rgb(51, 51, 51); font-family: &#39;Microsoft YaHei&#39;; font-size: 14px; white-space: normal; background-color: rgb(255, 255, 255);">除了在寿光软件园设置运营总部、研发中心、营销中心外，海联还在浙江宁波、山东青岛和河北石家庄设有研发中心。</p><p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; line-height: 25px; text-indent: 2em; color: rgb(51, 51, 51); font-family: &#39;Microsoft YaHei&#39;; font-size: 14px; white-space: normal; background-color: rgb(255, 255, 255);">公司一直致力于建立一套有序的、创新的、可持续发展的管理体制和发展模式，立志成为IT领域里卓越的技术型、集成型、服务型的企业。</p><p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; line-height: 25px; text-indent: 2em; color: rgb(51, 51, 51); font-family: &#39;Microsoft YaHei&#39;; font-size: 14px; white-space: normal; background-color: rgb(255, 255, 255);">雄厚的资金实力、强大的研发能力、专业的7X24小时运营维护支持，保障了云平台的安全、稳定和高效运行；庞大用户群体所形成的规模经济效应，则能够大幅度降低单一用户的使用成本，使企业客户真正能够以低廉的使用费获得高品质服务...</p><p><br/></p>', null, N'SYS_BUSSINESSCUSTOMER', N'2016-06-18 08:35:39')
INSERT INTO [dbo].[COM_CONTENT] ([ID], [FK_RELATIONID], [CONTENT], [CONTENTBLOB], [FK_TABLE], [CREATEDATE]) VALUES (2, N'faad6c82-70e0-4a32-a729-92fe755862c3', N'<p>海联官网建设 &nbsp;项目需求以及所需文档请查看项目文档</p>', null, N'PRO_PROJECTS', N'2016-06-20 10:32:43')
INSERT INTO [dbo].[COM_CONTENT] ([ID], [FK_RELATIONID], [CONTENT], [CONTENTBLOB], [FK_TABLE], [CREATEDATE]) VALUES (3, N'b33cdd33-48aa-4fdb-b63c-12979d702145', N'<p>官网建设 具体需求请查看项目文档</p>', null, N'PRO_PROJECTS', N'2016-06-21 08:22:40')
INSERT INTO [dbo].[COM_CONTENT] ([ID], [FK_RELATIONID], [CONTENT], [CONTENTBLOB], [FK_TABLE], [CREATEDATE]) VALUES (4, N'94c1de63-7431-4956-97e5-2969389d68d8', N'<p>课后后来会哦呼呼哈</p>', null, N'SYS_BUSSINESSCUSTOMER', N'2016-06-21 14:27:07')
INSERT INTO [dbo].[COM_CONTENT] ([ID], [FK_RELATIONID], [CONTENT], [CONTENTBLOB], [FK_TABLE], [CREATEDATE]) VALUES (5, N'f820ea0c-f4d3-4b35-bfc4-13036ccb2f8b', N'<p>前往人群为日期2016-6-21人</p>', null, N'PRO_PROJECTS', N'2016-06-21 14:36:15')
INSERT INTO [dbo].[COM_CONTENT] ([ID], [FK_RELATIONID], [CONTENT], [CONTENTBLOB], [FK_TABLE], [CREATEDATE]) VALUES (6, N'f33c0b9c-164d-44fc-93f6-3b1da027ef50', N'<p>李文海 你妹的</p>', null, N'MAIL_OUTBOX', N'2016-06-24 10:06:55')
INSERT INTO [dbo].[COM_CONTENT] ([ID], [FK_RELATIONID], [CONTENT], [CONTENTBLOB], [FK_TABLE], [CREATEDATE]) VALUES (7, N'7572105a-8713-41f6-80e0-02a92d85ee96', N'<p>娶你大爷的</p>', null, N'MAIL_OUTBOX', N'2016-06-24 18:09:11')
INSERT INTO [dbo].[COM_CONTENT] ([ID], [FK_RELATIONID], [CONTENT], [CONTENTBLOB], [FK_TABLE], [CREATEDATE]) VALUES (8, N'06aeaf26-ee8b-43a2-81b3-2997a62f3575', N'<p>qweqeqweqwe</p>', null, N'MAIL_OUTBOX', N'2016-06-25 09:24:27')
INSERT INTO [dbo].[COM_CONTENT] ([ID], [FK_RELATIONID], [CONTENT], [CONTENTBLOB], [FK_TABLE], [CREATEDATE]) VALUES (1006, N'5fe8c156-e8d7-4394-a604-bf74e432a172', N'<table data-sort="sortDisabled" style="width:100%;font-size:13px"><tbody><tr class="firstRow"><td width="264" style="word-break:break-all">个人项目名称</td><td colspan="3" style="word-break: break-all;">sfsfsd</td></tr><tr><td width="264" style="word-break:break-all">个人项目进度</td><td colspan="3" style="word-break: break-all;">fsdfsdf</td></tr><tr><td width="264" valign="middle" rowspan="2" colspan="1" style="word-break:break-all">日常例行工作</td><td width="264" style="word-break:break-all" align="center"><strong>工作内容详细及完成情况</strong></td><td rowspan="1" colspan="2" style="word-break:break-all" align="center"><strong>问题解决方案详细</strong><br/></td></tr><tr><td style="word-break: break-all;"><p><br/></p><p>sdfsdfsdf</p><p><br/></p></td><td width="264" colspan="2" style="word-break: break-all;"><p><br/></p><p><br/></p><p>sfsdfs</p></td></tr><tr><td width="264" style="word-break:break-all">当日工作总结</td><td valign="top" rowspan="1" colspan="3" style="word-break: break-all;"><p><br/></p><p>fsdfsdf</p><p><br/></p></td></tr><tr><td width="264" style="word-break:break-all">明日工作计划</td><td valign="top" rowspan="1" colspan="3" style="word-break: break-all;"><p><br/></p><p>sfsdfsd</p><p><br/></p></td></tr><tr><td width="264" style="word-break:break-all">建议或说明事项</td><td valign="top" rowspan="1" colspan="3" style="word-break: break-all;"><p>fsdfsd</p><p><br/></p><p><br/></p></td></tr></tbody></table>', null, N'COM_DAILYS', N'2016-06-27 08:57:49')
SET IDENTITY_INSERT [dbo].[COM_CONTENT] OFF
